#!/usr/bin/env python3
# Copyright (c) 2025 DebVisor contributors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Initial migration

Revision ID: 4dd17a47cb28
Revises:
Create Date: 2025-12-08 11:09:24.947576

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision="4dd17a47cb28"
_down_revision=None
_branch_labels=None
_depends_on=None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "node",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.String(length=36), nullable=False),
        sa.Column("hostname", sa.String(length=253), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("mac_address", sa.String(length=17), nullable=True),
        sa.Column("cpu_cores", sa.Integer(), nullable=True),
        sa.Column("memory_gb", sa.Integer(), nullable=True),
        sa.Column("storage_gb", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("last_heartbeat", sa.DateTime(), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("rack", sa.String(length=100), nullable=True),
        sa.Column("labels", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("node", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_node_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_node_hostname"), ["hostname"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_node_node_id"), ["node_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_node_status"), ["status"], unique=False)

    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("last_activity", sa.DateTime(), nullable=True),
        sa.Column("api_key_hash", sa.String(length=255), nullable=True),
        sa.Column("api_key_created", sa.DateTime(), nullable=True),
        sa.Column("api_key_last_used", sa.DateTime(), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=True),
        sa.Column("mfa_secret", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key_hash"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_user_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_is_admin"), ["is_admin"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("operation", sa.String(length=50), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("request_data", sa.Text(), nullable=True),
        sa.Column("response_data", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("signature", sa.String(length=64), nullable=True),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column("compliance_tags", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("rpc_service", sa.String(length=50), nullable=True),
        sa.Column("rpc_method", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_log_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_operation"), ["operation"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_resource_id"), ["resource_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_resource_type"), ["resource_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("source_vm", sa.String(length=255), nullable=True),
        sa.Column("source_volume", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("size_gb", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("progress_percent", sa.Integer(), nullable=True),
        sa.Column("retention_days", sa.Integer(), nullable=True),
        sa.Column("is_encrypted", sa.Boolean(), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_snapshot_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_snapshot_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_snapshot_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_snapshot_node_id"), ["node_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_snapshot_snapshot_id"), ["snapshot_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_snapshot_status"), ["status"], unique=False
        )

    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_snapshot_status"))
        batch_op.drop_index(batch_op.f("ix_snapshot_snapshot_id"))
        batch_op.drop_index(batch_op.f("ix_snapshot_node_id"))
        batch_op.drop_index(batch_op.f("ix_snapshot_name"))
        batch_op.drop_index(batch_op.f("ix_snapshot_expires_at"))
        batch_op.drop_index(batch_op.f("ix_snapshot_created_at"))

    op.drop_table("snapshot")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_status"))
        batch_op.drop_index(batch_op.f("ix_audit_log_resource_type"))
        batch_op.drop_index(batch_op.f("ix_audit_log_resource_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_operation"))
        batch_op.drop_index(batch_op.f("ix_audit_log_created_at"))

    op.drop_table("audit_log")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.drop_index(batch_op.f("ix_user_is_admin"))
        batch_op.drop_index(batch_op.f("ix_user_is_active"))
        batch_op.drop_index(batch_op.f("ix_user_email"))
        batch_op.drop_index(batch_op.f("ix_user_created_at"))

    op.drop_table("user")
    with op.batch_alter_table("node", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_node_status"))
        batch_op.drop_index(batch_op.f("ix_node_node_id"))
        batch_op.drop_index(batch_op.f("ix_node_hostname"))
        batch_op.drop_index(batch_op.f("ix_node_created_at"))

    op.drop_table("node")
    # ### end Alembic commands ###
