# !/usr/bin/env python3
# Copyright (c) 2025 DebVisor contributors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# !/usr/bin/env python3

# !/usr/bin/env python3


# !/usr/bin/env python3

# !/usr/bin/env python3


# !/usr/bin/env python3

# !/usr/bin/env python3


# !/usr/bin/env python3

# !/usr/bin/env python3


# !/usr/bin/env python3


# !/usr/bin/env python3


# !/usr/bin/env python3


# !/usr/bin/env python3

# !/usr/bin/env python3

# !/usr/bin/env python3

# !/usr/bin/env python3

# !/usr/bin/env python3

# !/usr/bin/env python3

# !/usr/bin/env python3

# !/usr/bin/env python3

# !/usr/bin/env python3

# !/usr/bin/env python3

# !/usr/bin/env python3

# !/usr/bin/env python3

# !/usr/bin/env python3

# !/usr/bin/env python3

# !/usr/bin/env python3

# !/usr/bin/env python3


"""add indexes to node snapshot and audit_log

Revision ID: e715b9926fa5
Revises: 4dd17a47cb28
Create Date: 2025-12-08 11:10:00.000000

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'e715b9926fa5'
_down_revision = '4dd17a47cb28'
_branch_labels = None
_depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_rpc_method'), ['rpc_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_rpc_service'), ['rpc_service'], unique=False)

    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_mac_address'), ['mac_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_region'), ['region'], unique=False)

    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_source_vm'), ['source_vm'], unique=False)

    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_source_vm'))

    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_region'))
        batch_op.drop_index(batch_op.f('ix_node_mac_address'))
        batch_op.drop_index(batch_op.f('ix_node_ip_address'))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_rpc_service'))
        batch_op.drop_index(batch_op.f('ix_audit_log_rpc_method'))
        batch_op.drop_index(batch_op.f('ix_audit_log_ip_address'))

    # ### end Alembic commands ###
