apiVersion: v1
kind: Namespace
metadata:
  name: argocd-debvisor
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: security-remediation-flow
  namespace: argocd-debvisor
spec:
  entrypoint: alert-to-remediation
  serviceAccountName: debvisor-automation
  arguments:
    parameters:
    - name: awx-base-url
      value: "https://awx.debvisor.local"
    - name: prometheus-base-url
      value: "http://prometheus.debvisor-monitoring.svc:9090"
    - name: awx-token
      value: ""
    - name: dry-run
      value: "false"
    - name: alert-sink
      value: "http://alert-sink.debvisor-monitoring.svc:8080/failed"
  
  templates:
  - name: alert-to-remediation
    steps:
    - - name: receive-prometheus-alert
        template: webhook-receiver
    - - name: parse-alert-payload
        template: extract-context
        arguments:
          parameters:
          - name: alert-json
            value: "{{steps.receive-prometheus-alert.outputs.result}}"
        onFailure: alert-sink-failed
    - - name: trigger-awx-playbook
        template: awx-job-launcher
        arguments:
          parameters:
          - name: playbook-name
            value: "{{steps.parse-alert-payload.outputs.parameters.playbook}}"
          - name: extra-vars
            value: "{{steps.parse-alert-payload.outputs.parameters.vars}}"
          - name: dry-run
            value: "{{workflow.parameters.dry-run}}"
          - name: alert-name
            value: "{{steps.parse-alert-payload.outputs.parameters.alert_name}}"
        onFailure: alert-sink-failed
    - - name: verify-remediation
        template: check-metrics
        arguments:
          parameters:
          - name: metric-name
            value: "{{steps.parse-alert-payload.outputs.parameters.success_metric}}"
          - name: alert-name
            value: "{{steps.parse-alert-payload.outputs.parameters.alert_name}}"
        onFailure: alert-sink-failed
    - - name: audit-success
        template: log-remediation-audit
        arguments:
          parameters:
          - name: alert-name
            value: "{{steps.parse-alert-payload.outputs.parameters.alert_name}}"
          - name: playbook-name
            value: "{{steps.parse-alert-payload.outputs.parameters.playbook}}"
          - name: status
            value: "success"
  
  - name: alert-sink-failed
    steps:
    - - name: send-to-dlq
        template: dead-letter-queue
        arguments:
          parameters:
          - name: workflow-name
            value: "{{workflow.name}}"
          - name: error-message
            value: "{{workflow.status.message}}"
          - name: failure-node
            value: "{{workflow.status.nodes}}"
    - - name: audit-failure
        template: log-remediation-audit
        arguments:
          parameters:
          - name: alert-name
            value: "unknown"
          - name: playbook-name
            value: "unknown"
          - name: status
            value: "failed"
  
  - name: webhook-receiver
    http:
      url: "http://debvisor-webhook-receiver.debvisor-monitoring.svc:8080/alert"
      method: POST
    retryStrategy:
      limit: 3
      retryPolicy: "Always"
      backoff:
        duration: "5s"
        factor: 2
    timeoutSeconds: 300
  
  - name: extract-context
    inputs:
      parameters:
      - name: alert-json
    script:
      image: python:3.11-slim
      command: [python]
      source: |
        import json
        import sys
        import os
        from datetime import datetime
        
        raw = '{{inputs.parameters.alert-json}}'
        try:
            alert = json.loads(raw)
        except json.JSONDecodeError as exc:
            sys.stderr.write(f"[{datetime.now().isoformat()}] AUDIT: Failed to decode alert JSON: {exc}\n")
            sys.exit(1)

        labels = alert.get('labels') or {}
        annotations = alert.get('annotations') or {}

        alert_name = labels.get('alertname')
        if not alert_name:
            alert_name = 'UnknownAlert'
        
        playbook_map = {
          'MFAComplianceViolation': 'enforce-mfa.yml',
          'HostCompromised': 'quarantine-host.yml',
          'MaliciousIPDetected': 'block-ips.yml',
          'UnknownAlert': 'default-remediation.yml',
        }
        
        playbook = playbook_map.get(alert_name, 'default-remediation.yml')
        vars = annotations
        success_metric = f"debvisor_{alert_name.lower()}_resolved"
        
        # Log extraction with timestamp
        sys.stderr.write(f"[{datetime.now().isoformat()}] AUDIT: Extracted alert: {alert_name} -> {playbook}\n")
        
        print(json.dumps({
          'alert_name': alert_name,
          'playbook': playbook,
          'vars': vars,
          'success_metric': success_metric
        }))
    timeoutSeconds: 60
  
  - name: awx-job-launcher
    inputs:
      parameters:
      - name: playbook-name
      - name: extra-vars
      - name: dry-run
      - name: alert-name
    http:
      url: "{{workflow.parameters.awx-base-url}}/api/v2/job_templates/{{inputs.parameters.playbook-name}}/launch/"
      method: POST
      headers:
      - name: Authorization
        value: "Bearer {{workflow.parameters.awx-token}}"
      - name: Content-Type
        value: "application/json"
      body: |
        {
          "extra_vars": {{inputs.parameters.extra-vars}},
          "dry_run": {{inputs.parameters.dry-run}},
          "extra_vars": {
            "audit_id": "{{workflow.name}}-{{inputs.parameters.alert-name}}",
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          }
        }
    retryStrategy:
      limit: 3
      retryPolicy: "Always"
      backoff:
        duration: "10s"
        factor: 2
    timeoutSeconds: 1800
  
  - name: check-metrics
    inputs:
      parameters:
      - name: metric-name
      - name: alert-name
    retryStrategy:
      limit: 10
      retryPolicy: "Always"
      backoff:
        duration: "30s"
        factor: 1.5
    script:
      image: curlimages/curl:latest
      command: [sh]
      source: |
        metric_name="{{inputs.parameters.metric-name}}"
        alert_name="{{inputs.parameters.alert-name}}"
        attempts=0
        
        while [ $attempts -lt 10 ]; do
          response=$(curl -s "{{workflow.parameters.prometheus-base-url}}/api/v1/query?query=${metric_name}" 2>/dev/null)
          
          if echo "$response" | grep -q '"value":\[.*,.*"1"\]'; then
            echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] AUDIT: Remediation verified for ${alert_name}: metric ${metric_name} = 1"
            exit 0
          fi
          
          attempts=$((attempts + 1))
          if [ $attempts -lt 10 ]; then
            echo "Verification attempt $attempts/10 failed, retrying..."
            sleep 30
          fi
        done
        
        echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] AUDIT: Failed to verify remediation for ${alert_name} after 10 attempts"
        exit 1
    timeoutSeconds: 600
  
  - name: dead-letter-queue
    inputs:
      parameters:
      - name: workflow-name
      - name: error-message
      - name: failure-node
    http:
      url: "{{workflow.parameters.alert-sink}}"
      method: POST
      headers:
      - name: Content-Type
        value: "application/json"
      body: |
        {
          "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "workflow_name": "{{inputs.parameters.workflow-name}}",
          "error": "{{inputs.parameters.error-message}}",
          "failed_node": "{{inputs.parameters.failure-node}}",
          "namespace": "{{workflow.namespace}}",
          "requires_manual_intervention": true
        }
    retryStrategy:
      limit: 2
      retryPolicy: "Always"
      backoff:
        duration: "5s"
        factor: 2
    timeoutSeconds: 60
  
  - name: log-remediation-audit
    inputs:
      parameters:
      - name: alert-name
      - name: playbook-name
      - name: status
    script:
      image: python:3.11-slim
      command: [python]
      source: |
        import json
        from datetime import datetime
        
        audit_entry = {
          "timestamp": datetime.utcnow().isoformat(),
          "workflow_id": "{{workflow.uid}}",
          "workflow_name": "{{workflow.name}}",
          "alert_name": "{{inputs.parameters.alert-name}}",
          "playbook": "{{inputs.parameters.playbook-name}}",
          "status": "{{inputs.parameters.status}}",
          "namespace": "{{workflow.namespace}}"
        }
        
        print(json.dumps(audit_entry))
    timeoutSeconds: 30
