name: 'Grafana dashboard smoke test'
description: 'Wait for Grafana, upload dashboards, and verify DebVisor dashboards are searchable.'
inputs:
  dashboards-path:
    description: 'Glob for dashboard JSON files'
    required: false
    default: 'monitoring/grafana/dashboards/*.json'
    
runs:
  using: 'composite'
  steps:
    - name: Wait for Grafana
      shell: bash
      run: |
        for i in $(seq 1 30); do
          if curl -sf http://localhost:3000/api/health >/dev/null; then
            exit 0
          fi
          sleep 2
        done
        echo "Grafana did not become healthy in time" >&2
        exit 
        
    - name: Upload dashboards
      shell: bash
      run: |
        for f in ${{ inputs.dashboards-path }}; do
          curl -sf -X POST http://admin:admin@localhost:3000/api/dashboards/db \
            -H 'Content-Type: application/json' -d @"$f";
        done

    - name: Verify search
      shell: bash
      run: |
        resp=$(curl -sf http://admin:admin@localhost:3000/api/search?query=DebVisor)
        echo "$resp" | jq .
        count=$(echo "$resp" | jq 'length')
        if [ "$count" -lt 1 ]; then
          echo "Expected at least one DebVisor dashboard in Grafana search" >&2
          exit 1
        fi
